apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-container
        image: sharoz3111/rails-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          value: dummy_secret_key_base
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: postgres
        - name: DATABASE_URL
          value: postgres://postgres:mypassword@postgres:5432/myapp_development

